name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up LaTeX environment
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive texlive-lang-german texlive-latex-extra latexmk 

    - name: Compile LaTeX document
      run: |
        latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex

    - name: Commit and push PDF
      if: success()
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add main.pdf -f
        git commit -m "Add generated PDF [skip ci]"
        git push

    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: main.pdf
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Release PDF
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        files: main.pdf
        tag_name: ${{ steps.date.outputs.date}}
        make_latest: true
